language: python
arch:
 - amd64
 - ppc64le
python:
  # - "2.7"
  # - "pypy"
  # - "3.4"
  # - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# Install numpy, then BioPython
# BioPython doesn't always play well with pip install.
install:
  - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -q numpy; fi"
  - "pip install -q biopython nose pygtrie"
  - "pip install ."

script:
  - seqmagick --version
  - nosetests

notifications:
  email:
    - noah.hoffman@gmail.com
