=========
seqmagick
=========

We often have to convert sequence files between formats and do little
manipulations on them, and it's not worth writing scripts for that.
``seqmagick`` is a kickass little utility to expose the file format conversion
in BioPython in a convenient way.  Instead of having a big mess of scripts,
there is one that takes arguments.

`Documentation`_.

``seqmagick`` is free software under the GPL v3.

.. _`Documentation`: http://fhcrc.github.com/seqmagick/

